#ifndef PS2_IRX_IMAGE_FORMAT_H
#define PS2_IRX_IMAGE_FORMAT_H

#define IRXIMG_MAGIC "PS2IRX01"
#define IRXIMG_MAGIC_SIZE 8u
#define IRXIMG_VERSION 1u
#define IRXIMG_HEADER_SIZE 44u
#define IRXIMG_ENTRY_SIZE 20u
#define IRXIMG_ALIGNMENT 16u
#define IRXIMG_MAX_ENTRIES 128u

#endif
